baseURL = 'https://amirali-az.github.io/periodictable.github.io'
languageCode = 'en-us'
title = 'PeriodicTable'
theme = 'hugo-elate-theme'

[params]

  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = "PeriodicTable"
    home = "Home"
    work = "Work"
    about = "About"
    # You can add custom links before or after the default links
    # Assign a weight to define the order

    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10

  # Hero section
  [params.hero]
    title = "PeriodicTable"
    subtitle = 'A simple periodic table app for chemistery lovers!'

  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Release"
    description = "Get latest releases"
    url = "https://github.com/AmirAli-AZ/PeriodicTable/releases"
    button = "Get"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Repository"
    description = "Get the source code and if you have an idea you can tell us or contribute to the project!"
    url = "https://github.com/AmirAli-AZ/PeriodicTable/"
    button = "Go"
    icon = "icon-github"
    img = "img_8.jpg"

  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "The Features Of PeriodicTable And What Can It Does"

    [[params.work.row]]
      img = "Screenshot_20230121_181524.png"
      alt = "LightThemeScreenshot"
      title = "LightTheme"
      subtitle = "PeriodicTable is avilable in light theme"

    [[params.work.row]]
      img = "Screenshot_20230121_181512.png"
      alt = "DarkThemeScreenshot"
      title = "DarkTheme"
      subtitle = "PeriodicTable is avilable in dark theme"

    [[params.work.row]]
      img = "Screenshot_20230121_181603-1.png"
      alt = "InfoDialog"
      title = "Element Information"
      subtitle = "See a summary information of elements"

    [[params.work.row]]
      img = "Screenshot_20230121_181625.png"
      alt = "Bohr'sModelScreenshot"
      title = "Bohr's Model"
      subtitle = "See a bohr's model of elements"

    [[params.work.row]]
      img = "wide-periodic-table.png"
      alt = "WideLayout"
      title = "Wide Layout"
      subtitle = "See periodic table in a wide layout"

  [params.about]
    enable = true
    title = "About Shahriari Programmers"
    description = "We are a group of programmers from shahriari highschool in Iran with 3 years of programming and designing experience"

    [[params.about.item]]
      name = "Amir Ali Azimi"
      position = "Programmer"
      description = "16 years old programmer from shahriari highschool in Iran"
      img = "person1.jpg"
      alt = "AmirAliAzimi"
      social = [
        ["icon-github", "https://github.com/AmirAli-AZ/"]
      ]

    [[params.about.item]]
      name = "Mohammad Javad Rahimi"
      position = "Designer"
      description = "Designer from shahriari highschool in Iran"
      img = "person2.jpg"
      alt = "MohammadJavadRahimi"
      social = []

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy;2023 ShahriariProgrammers'
    links = []
